version: '3.8'
services:
  user-service:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=dbusers
      - DB_USER=user_db
      - DB_PASSWORD=12345
      - JWT_SECRET=supersecretkey
